version: '3'

services:
  postgres:
    image: 'postgres'
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Cloud
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - application-network

  webapp:
    build: ./WebApp
    container_name: webapp
    ports:
        - "8081:8081"
    networks:
      - application-network
    environment:
      DATABASE_DOMAIN : postgres
      DATABASE_PORT : 5432
      POSTGRES_PASSWORD : root
      POSTGRES_USER : postgres
      POSTGRES_DB : Cloud
    depends_on:
      - postgres

networks:
  application-network:
    
volumes:
  pgdata:
